server:
  port: 0

spring:
  profiles:
    active: ${active_profile}
  application:
    name: test
  config:
    import: optional:configserver:${config.server}
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    metadata-map:
      profile: ${spring.profiles.active:${spring.profiles.default}}
  client:
    service-url:
      defaultZone: ${eureka.server.url}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health
