server:
  port: 0

spring:
  profiles:
    default: default
    active: dev, test, data
  application:
    name: test
  config:
    import: optional:configserver:http://localhost:8080

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    metadata-map:
      profile: ${spring.profiles.active:${spring.profiles.default}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
