server:
  port: 8080

spring:
  application:
    name: application
  config:
    import: optional:configserver:${config.server}
  cloud:
    config:
      name: application
  profiles:
    active: local, test
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    metadata-map:
      profile: ${spring.profiles.active:${spring.profiles.default}}
  client:
    service-url:
      defaultZone: ${eureka.server.url}
    region: ${eureka.region}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health
